GO


--MERGE generated by 'sp_generate_merge' stored procedure, Version 0.93
--Originally by Vyas (http://vyaskn.tripod.com): sp_generate_inserts (build 22)
--Adapted for SQL Server 2008/2012 by Daniel Nolan (http://danere.com)

SET NOCOUNT ON

SET IDENTITY_INSERT [dbo].[Employee] ON

ALTER TABLE [dbo].[Employee] NOCHECK CONSTRAINT ALL
MERGE INTO [dbo].[Employee] AS [Target]
USING (VALUES
  (1,N'Vinod Kumar Sunkara',N'IT',N'vinod.svk89@gmail.com')
 ,(2,N'Naveen',N'IT',N'vinod@gmail.com')
 ,(3,N'Sneha',N'IT',N'sneha@gmail.com')
 ,(4,N'Ravi',N'IT',N'ravi@gmail.com')
 ,(5,N'Sam',N'IT',N'sam@gmail.com')
 ,(6,N'Samson',N'IT',N'samson@gmail.com')
 ,(7,N'Smith',N'IT',N'smith@gmail.com')
 ,(8,N'Rajesh',N'IT',N'rajesh@gmail.com')
 ,(9,N'John',N'IT',N'john@gmail.com')
) AS [Source] ([Id],[Fullname],[Department],[Email])
ON ([Target].[Id] = [Source].[Id])
WHEN MATCHED AND (
	NULLIF([Source].[Fullname], [Target].[Fullname]) IS NOT NULL OR NULLIF([Target].[Fullname], [Source].[Fullname]) IS NOT NULL OR 
	NULLIF([Source].[Department], [Target].[Department]) IS NOT NULL OR NULLIF([Target].[Department], [Source].[Department]) IS NOT NULL OR 
	NULLIF([Source].[Email], [Target].[Email]) IS NOT NULL OR NULLIF([Target].[Email], [Source].[Email]) IS NOT NULL) THEN
 UPDATE SET
  [Fullname] = [Source].[Fullname], 
  [Department] = [Source].[Department], 
  [Email] = [Source].[Email]
WHEN NOT MATCHED BY TARGET THEN
 INSERT([Id],[Fullname],[Department],[Email])
 VALUES([Source].[Id],[Source].[Fullname],[Source].[Department],[Source].[Email])
WHEN NOT MATCHED BY SOURCE THEN 
 DELETE
;
GO
DECLARE @mergeError int
 , @mergeCount int
SELECT @mergeError = @@ERROR, @mergeCount = @@ROWCOUNT
IF @mergeError != 0
 BEGIN
 PRINT 'ERROR OCCURRED IN MERGE FOR [dbo].[Employee]. Rows affected: ' + CAST(@mergeCount AS VARCHAR(100)); -- SQL should always return zero rows affected
 END
ELSE
 BEGIN
 PRINT '[dbo].[Employee] rows affected by MERGE: ' + CAST(@mergeCount AS VARCHAR(100));
 END
GO

ALTER TABLE [dbo].[Employee] CHECK CONSTRAINT ALL
GO
SET IDENTITY_INSERT [dbo].[Employee] OFF
GO
SET NOCOUNT OFF
GO